#Deriving the latest base image
FROM python:latest
WORKDIR /Users/adlfkl/Desktop/SGH/RTA/Project/producer
COPY producer.py ./
COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt
COPY . .
CMD [ "python", "./producer.py"]